# Generated by Django 5.0.1 on 2024-01-17 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMemberClub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedMemberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=250, null=True)),
                ('Dob', models.DateTimeField(null=True)),
                ('Resphone', models.CharField(max_length=20, null=True)),
                ('Altermobileno', models.CharField(max_length=20, null=True)),
                ('Resaddress', models.CharField(max_length=300, null=True)),
                ('Officeno', models.CharField(max_length=255, null=True)),
                ('Profilepic', models.ImageField(null=True, upload_to='pics')),
                ('Signature', models.ImageField(null=True, upload_to='pics')),
                ('Creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('relation', models.CharField(max_length=100, null=True)),
                ('contactno', models.CharField(max_length=20, null=True)),
                ('homeaddress', models.CharField(max_length=300, null=True)),
                ('Spousename', models.CharField(max_length=200, null=True)),
                ('Spousedob', models.DateTimeField(null=True)),
                ('Childname', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=300, null=True)),
                ('Country', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Postalcode', models.CharField(max_length=10, null=True)),
                ('Addresstype', models.CharField(max_length=50, null=True)),
                ('Additionalinfo', models.TextField(null=True)),
                ('Businessname', models.CharField(max_length=100, null=True)),
                ('Businessdetails', models.TextField(null=True)),
                ('Businessaddress', models.CharField(max_length=100, null=True)),
                ('Businesscity', models.CharField(max_length=20, null=True)),
                ('Businessemail', models.CharField(max_length=300, null=True)),
                ('Businesspostalcode', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
