# Generated by Django 5.0.1 on 2024-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMemberClub', '0002_proposedmemberdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Additionalinfo',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Addresstype',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Businessaddress',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Businesscity',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Businessdetails',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Businessemail',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Businessname',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Businesspostalcode',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Childname',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='City',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Postalcode',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Spousedob',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Spousename',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='State',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='contactno',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='homeaddress',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='relation',
        ),
        migrations.AlterField(
            model_name='proposedmemberdata',
            name='Country',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
