# Generated by Django 5.0.1 on 2024-01-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMemberClub', '0003_remove_proposedmemberdata_additionalinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedmemberdata',
            name='Creation_date',
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Additionalinfo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Addresstype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Businessaddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Businesscity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Businessdetails',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Businessemail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Businessname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Businesspostalcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Childname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Postalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Spousedob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='Spousename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='contactno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='homeaddress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='proposed_memberaddressdata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPMemberClub.memberaddressdata'),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='proposed_memberbusinessdata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPMemberClub.memberbusinessdata'),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='proposed_memberdata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPMemberClub.memberdata'),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='proposed_memberfamilydata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPMemberClub.memberfamilydata'),
        ),
        migrations.AddField(
            model_name='proposedmemberdata',
            name='relation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proposedmemberdata',
            name='Country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
